[workspace]

members = [
    "bin/node",
    "bin/runtime",
    "finality-aleph",
    "pallet",
    "primitives",
    "flooder",
]

exclude = [
  # "flooder",
  "e2e-tests",
  "common",
  "local-tests/send-runtime"
]
