[workspace]

members = [
    "bin/node",
    "bin/runtime",
    "finality-aleph",
    "pallet",
    "primitives",
    "flooder",
    "common"
]

exclude = [
  # "flooder",
  "e2e-tests",
  # "common"
]
