[package]
name = "aleph-node"
version = "0.9.0"
authors = ["Cardinal Cryptography"]
description = "Aleph node binary"
edition = "2021"
build = "build.rs"
homepage = "https://alephzero.org"
repository = "https://github.com/aleph-zero-foundation/aleph-node"
license = "GPL-3.0-or-later"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "aleph-node"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
log = "0.4"
serde = "1.0"
serde_json = "1.0"
futures = "0.3"
hex = "0.4"
hex-literal = "0.3"
libp2p = "0.49.0"
thiserror = "1.0"

sp-application-crypto = { git = "https://github.com/fixxxedpoint/substrate.git", branch = "unbounded_channel_FIX" }
sc-block-builder = { git = "https://github.com/fixxxedpoint/substrate.git", branch = "unbounded_channel_FIX" }
sc-chain-spec = { git = "https://github.com/fixxxedpoint/substrate.git", branch = "unbounded_channel_FIX"}
sc-cli = { git = "https://github.com/fixxxedpoint/substrate.git", branch = "unbounded_channel_FIX" }
sp-core = { git = "https://github.com/fixxxedpoint/substrate.git", branch = "unbounded_channel_FIX" }
sc-executor = { git = "https://github.com/fixxxedpoint/substrate.git", branch = "unbounded_channel_FIX" }
sc-service = { git = "https://github.com/fixxxedpoint/substrate.git", branch = "unbounded_channel_FIX" }
sc-telemetry = { git = "https://github.com/fixxxedpoint/substrate.git", branch = "unbounded_channel_FIX" }
sc-keystore = { git = "https://github.com/fixxxedpoint/substrate.git", branch = "unbounded_channel_FIX" }
sp-keystore = { git = "https://github.com/fixxxedpoint/substrate.git", branch = "unbounded_channel_FIX" }
sp-inherents = { git = "https://github.com/fixxxedpoint/substrate.git", branch = "unbounded_channel_FIX" }
sc-basic-authorship = { git = "https://github.com/fixxxedpoint/substrate.git", branch = "unbounded_channel_FIX" }
sc-network = { git = "https://github.com/fixxxedpoint/substrate.git", branch = "unbounded_channel_FIX" }
sc-transaction-pool = { git = "https://github.com/fixxxedpoint/substrate.git", branch = "unbounded_channel_FIX" }
sp-transaction-pool = { git = "https://github.com/fixxxedpoint/substrate.git", branch = "unbounded_channel_FIX" }
sc-transaction-pool-api = { git = "https://github.com/fixxxedpoint/substrate.git", branch = "unbounded_channel_FIX" }
sc-consensus-aura = { git = "https://github.com/fixxxedpoint/substrate.git", branch = "unbounded_channel_FIX" }
sp-consensus-aura = { git = "https://github.com/fixxxedpoint/substrate.git", branch = "unbounded_channel_FIX" }
sp-consensus = { git = "https://github.com/fixxxedpoint/substrate.git", branch = "unbounded_channel_FIX" }
sc-consensus = { git = "https://github.com/fixxxedpoint/substrate.git", branch = "unbounded_channel_FIX" }
sc-client-api = { git = "https://github.com/fixxxedpoint/substrate.git", branch = "unbounded_channel_FIX" }
sp-runtime = { git = "https://github.com/fixxxedpoint/substrate.git", branch = "unbounded_channel_FIX" }
sp-timestamp = { git = "https://github.com/fixxxedpoint/substrate.git", branch = "unbounded_channel_FIX" }
pallet-staking = { git = "https://github.com/fixxxedpoint/substrate.git", branch = "unbounded_channel_FIX" }
try-runtime-cli = { git = "https://github.com/fixxxedpoint/substrate.git", branch = "unbounded_channel_FIX", optional = true }
sc-consensus-slots = { git = "https://github.com/fixxxedpoint/substrate.git", branch = "unbounded_channel_FIX" }
sp-arithmetic = { git = "https://github.com/fixxxedpoint/substrate.git", branch = "unbounded_channel_FIX" }
sp-io = { git = "https://github.com/fixxxedpoint/substrate.git", branch = "unbounded_channel_FIX" }

frame-benchmarking-cli = { git = "https://github.com/fixxxedpoint/substrate.git", branch = "unbounded_channel_FIX", optional = true }
frame-benchmarking = { git = "https://github.com/fixxxedpoint/substrate.git", branch = "unbounded_channel_FIX", optional = true }

aleph-runtime = { path = "../runtime" }
finality-aleph = { path = "../../finality-aleph" }
aleph-primitives = { package = "primitives", path = "../../primitives" }
network-clique = { package = "network-clique", path = "../../clique" }

# These dependencies are used for the node's RPCs
jsonrpsee = { version = "0.16.2", features = ["server"] }
sc-rpc = { git = "https://github.com/fixxxedpoint/substrate.git", branch = "unbounded_channel_FIX" }
sp-api = { git = "https://github.com/fixxxedpoint/substrate.git", branch = "unbounded_channel_FIX" }
sc-rpc-api = { git = "https://github.com/fixxxedpoint/substrate.git", branch = "unbounded_channel_FIX" }
sp-blockchain = { git = "https://github.com/fixxxedpoint/substrate.git", branch = "unbounded_channel_FIX" }
sp-block-builder = { git = "https://github.com/fixxxedpoint/substrate.git", branch = "unbounded_channel_FIX" }
substrate-frame-rpc-system = { git = "https://github.com/fixxxedpoint/substrate.git", branch = "unbounded_channel_FIX" }
pallet-transaction-payment-rpc = { git = "https://github.com/fixxxedpoint/substrate.git", branch = "unbounded_channel_FIX" }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/fixxxedpoint/substrate.git", branch = "unbounded_channel_FIX" }

[features]
default = []
short_session = [
    "aleph-runtime/short_session",
    "aleph-primitives/short_session"
]
try-runtime = [
    "aleph-runtime/try-runtime",
    "try-runtime-cli/try-runtime",
]
enable_treasury_proposals = [
    "aleph-runtime/enable_treasury_proposals"
]
runtime-benchmarks = [
    "frame-benchmarking",
    "frame-benchmarking-cli/runtime-benchmarks",
    "aleph-runtime/runtime-benchmarks",
]
only_legacy = [
    "finality-aleph/only_legacy"
]

# Liminal-related features
liminal = [
    "aleph-runtime/liminal",
    "aleph-primitives/liminal-std",
]
liminal-try-runtime = [
    "liminal",
    "try-runtime",
    "aleph-runtime/liminal-try-runtime",
]
liminal-runtime-benchmarks = [
    "liminal",
    "runtime-benchmarks",
    "aleph-runtime/liminal-runtime-benchmarks"
]
