[rust]
lld = true

[build]
# rustflags = ["-C", "linker=lld", "-C", "target-cpu=cascadelake"]
# rustflags = ["-C", "target-cpu=cascadelake"]
# rustflags = ["-C", "linker=lld", "-C", "link-arg=-fuse-ld=lld", "-C", "target-cpu=cascadelake"]
# rustflags = ["-C", "link-arg=-fuse-ld=lld", "-C", "target-cpu=cascadelake"]
# target = "x86_64-unknown-linux-gnu"

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-fuse-ld=lld", "-C", "target-cpu=cascadelake"]
# linker = "lld"